name: vrp_kernels
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - numpy
  - pandas
  - pip
  - tqdm
  - tensorboard

  - pip:
    - tensorboard-logger
    - protobuf==3.20.3