python run.py \
--eval_only \
--problem tsp \
--graph_size 20 \
--step_method 2_opt \
--T_max 1000 \
--val_m 4 \
--val_size 10000 \
--load_path './pretrained/tsp_50/cauchy_32by2_new/epoch-199.pt' \
--init_val_met greedy \
--val_dataset  './datasets/tsp_100_10000.pkl' \
--kernel cauchy \
--hidden_dim 64 \
--embedding_dim 64 \
--no_tb \
--no_saving \
