python run.py \
--eval_only \
--problem tsp \
--graph_size 20 \
--step_method 2_opt \
--T_max 10000 \
--val_m 4 \
--val_size 10000 \
--load_path './pretrained/tsp_20_cauchy.pt' \
--init_val_met greedy \
--val_dataset  './datasets/tsp_20_10000.pkl' \
--kernel cauchy \
--hidden_dim 32 \
--embedding_dim 32 \
--no_tb \
--no_saving \
