python run.py \
--eval_only \
--problem tsp \
--graph_size 100 \
--step_method 2_opt \
--n_step 4 \
--T_max 5000 \
--val_m 1 \
--val_size 10000 \
--load_path './pretrained/tsp_100/cauchy_32by2_new/epoch-99.pt' \
--init_val_met greedy \
--val_dataset  './datasets/tsp_100_10000.pkl' \
--kernel cauchy \
--hidden_dim 32 \
--embedding_dim 32 \
--no_tb \
--no_saving \
